urls.py
# vim: ai ts=4 sts=4 et sw=4 encoding=utf-8

from django.conf.urls.defaults import patterns, include
from django.views.generic.simple import direct_to_template
from django.conf import settings

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
        (r'^accounts/login/$', 'django.contrib.auth.views.login'),
        (r'^accounts/logout/$', 'django.contrib.auth.views.logout', { 'next_page': '/' })
        )

urlpatterns += patterns('', (r'^admin/(.*)', admin.site.root))

urlpatterns += patterns('maplayers',
                        (r'^user_registration/$', 'views.user_registration'),
                        (r'^check_username/$','views.check_username'),
                        (r'^change_password/$', 'views.change_password'),
                        (r'^projects/bbox/(?P<left>.+)/(?P<bottom>.+)/(?P<right>.+)/(?P<top>.+)/$',
                         'views.projects_in_map'),
                        (r'^projects/nearby/(?P<left>.+)/(?P<bottom>.+)/(?P<right>.+)/(?P<top>.+)/$',
                         'views.nearby_projects'),
                         (r'^projects/id/(?P<project_id>\d+)/$', 'views.project'),
                         (r'^$', 'views.homepage'),
                         (r'^projects/search/$','views.projects_search'),
                         (r'^permission_denied/(?P<action>.+)/(?P<reason>.+)/$', direct_to_template,
                          {'template': 'permission_denied.html'}),
                         (r'^user_registration/success/$', direct_to_template, 
                          {'template' : 'registration_success.html', 'message' : 'User Created'}),
                         (r'^change_password/success/$', direct_to_template, 
                          {'template' : 'registration_success.html', 'message' : 'Password changed'}),
                         (r'^projects/tag/(?P<tag_term>.+)/$','views.projects_tag_search'),
                         (r'^projects/(?P<project_id>\d+)/comment/$','views.project_comment'),
                         (r'^project/comments/(?P<project_id>\d+)/all/(?P<mode>\w+)/$', 'views.all_comments'),
                         (r'^search_admin_unit/$', 'views.search_admin_units'),
                         (r'^kml_layers/$', 'views.kml_layers'),
                         (r'^country_details/$', 'views.country_details'),
                         (r'^projects/video/(?P<video_id>\d+)/$', 'views.project_video')
                         )
                         
urlpatterns += patterns('maplayers.project_admin_views',
                        (r'^add_project', 'add_project'),
                        (r'^edit_project/(?P<project_id>\d+)/$', 'edit_project'),
                        (r'^projects/upload/$', 'file_upload'),
                        (r'^projects/photo_upload/$','photo_upload'),
                        (r'^remove_photo/$','remove_photo'),
                        (r'^remove_attachment/$', 'remove_attachment'),
                        (r'^projects/publish/(?P<project_id>\d+)/$', 'publish_project'),
                        (r'^projects/unpublish/(?P<project_id>\d+)/$', 'unpublish_project'),
                        (r'^projects/reject/(?P<project_id>\d+)/$', 'reject_project'),
                        (r'^projects/delete/(?P<project_id>\d+)/$', 'delete_project'),
                        (r'^request_changes/(?P<project_id>\d+)/$', 'request_changes'),
                        (r'^projects/comments/(?P<project_id>\d+)/$', 'project_comments'),
                        (r'^projects/comments/publish/$', 'publish_comments'),
                        (r'^projects/comments/delete/$', 'delete_comments'),
                       )
 
urlpatterns += patterns('maplayers.admin_views',
                        (r'^my_projects/$', 'my_projects'),
                        (r'^projects_for_review/$', 'projects_for_review'),
                        (r'^projects/review_suggestions/(?P<project_id>\d+)/$', 'review_suggestions'),
                        (r'^admin_units/', 'admin_units'),
                        (r'^add_admin_unit/', 'add_administrative_unit'),
                        (r'^edit_admin_unit/(?P<id>\d+)/$', 'edit_administrative_unit'),
                        (r'^delete_admin_unit/$', 'delete_administrative_unit'),
                        (r'^add_kml/$', 'add_kml_file'),
                        (r'^delete_kml/(?P<id>\d+)/$', 'delete_kml'),
                       )

urlpatterns += patterns('',
                        (r'^tinymce/', include('tinymce.urls')))
                        

handler404 = 'maplayers.views.view_404'
handler500 = 'maplayers.views.view_500'

urlpatterns += patterns('',
                        (r'^static/(?P<path>.*)$', 
                         'django.views.static.serve',
                         {'document_root': 'static'})
                         )

maplayers/models.py
# vim: ai ts=4 sts=4 et sw=4 encoding=utf-8

from django.db import models
from django.contrib.auth.models import User, Group
from django.utils import text

import simplejson as json
from tagging.fields import TagField
from tagging.models import Tag
from tinymce import models as tinymce_models

import settings
from maplayers.countries import CountryField, COUNTRIES 
from maplayers.utils import is_empty
from maplayers.constants import GROUPS, PROJECT_STATUS

class Project(models.Model): 
    name = models.CharField(max_length=30, null=True, blank=True) 
    description = tinymce_models.HTMLField(null=True, blank=True)
    latitude = models.DecimalField(max_digits=10, decimal_places=7, null=True, blank=True)
    longitude = models.DecimalField(max_digits=10, decimal_places=7, null=True, blank=True)
    location = models.CharField(max_length=50, null=True, blank=True)
    website_url = models.URLField(null=True, blank=True)
    project_image = models.TextField(null=True, blank=True)
    imageset_feedurl = models.TextField(max_length=1000, null=True, blank=True)
    parent_project = models.ForeignKey('self', null=True, blank=True)
    status = models.CharField(max_length=50)
    created_by = models.ForeignKey(User)
    groups = models.ManyToManyField(Group)

    
    def _get_tags(self):
        '''
        Get tags seperated by spaces for the project
        '''
        tags = Tag.objects.get_for_object(self) 
        return " ".join([tag.name for tag in tags])
    
    def _set_tags(self, tag_list):
        '''
        Add tags to the tag list for the project
        '''
        Tag.objects.update_tags(self, tag_list)

    tags = property(_get_tags, _set_tags)  
      
    def contains_tag(self, tag):
        '''
        Return true if tag is in project's tag list
        '''
        if self.tags.split(" ").__contains__(tag):
            return True
        return False     
    
    def is_parent_project(self):
        '''
        Checks parent_project_id and returns true if not None
        '''
        if self.parent_project:
            return False
        return True
    
    def is_editable_by(self, user):
        if self.created_by == user: return True
        return self._check_user_groups(user)
        
    def is_publishable_by(self, user):
        return self._check_user_groups(user)
        
    def _check_user_groups(self, user):
        user_groups = set([group.name for group in user.groups.all()])
        if (user_groups & set((GROUPS.ADMINS, GROUPS.EDITORS_PUBLISHERS))) : return True
        return False
            
        
    def implementors_in_json(self):
        return json.dumps([implementor.name for implementor in Implementor.objects.filter(projects=self.id)])
    
    def sectors_in_json(self):
        return json.dumps([sector.name for sector in Sector.objects.filter(projects=self.id)])
    
    def __unicode__(self): 
        return ( 'No Name' if is_empty(self.name) else self.name)
        
    def snippet(self):
        truncated_description = self.description[0:130]
        return self.name + " : " + text.truncate_html_words(truncated_description, 100) + "..."
        
    def default_video(self):
        default_video_set = self.video_set.filter(default=True)
        if not default_video_set: return ''
        return default_video_set[0]
        
    def is_published(self):
        return PROJECT_STATUS.PUBLISHED == self.status 
    
    class Admin: 
        pass
 
class Link(models.Model):
    title = models.CharField(max_length=50)
    url = models.URLField()
    project = models.ForeignKey(Project)

    def __unicode__(self): 
        return self.title

    class Admin: 
        pass
    
class Resource(models.Model):
    title = models.CharField(max_length=50)
    filename = models.CharField(max_length=250)
    project = models.ForeignKey(Project)
    filesize = models.IntegerField()
    
    def file_size_in_kb(self):
        return "%s KB" % str(self.filesize/1024)

    def file_extension(self):
        return self.filename.split(".")[-1]

    def original_file_name(self):
        return "_".join(self.filename.split("_")[1:])
        
    @property
    def file_name_with_slash(self):
        return  settings.PROJECT_RESOURCES_URL + "/" + self.filename
    @property
    def is_audio_file(self):
        supported_audio_formats = ["mp3", "ogg"]
        file_type  =  self.filename.split(".")[-1]
        if supported_audio_formats.__contains__(file_type):
            return True
        return False

    def __unicode__(self): 
        return self.title

    class Admin: 
        pass
        
class Sector(models.Model):
    name = models.CharField(max_length=50)
    projects = models.ManyToManyField(Project, blank=True)
    
    def __unicode__(self): 
        return self.name

    class Admin: 
        pass
        
class Implementor(models.Model):
    name = models.CharField(max_length=50)
    projects = models.ManyToManyField(Project, blank=True)
    
    def __unicode__(self):
        return self.name
        
    class Admin:
        pass

class AdministrativeUnit(models.Model):
    name = models.CharField(max_length = 20)
    region_type = models.CharField(max_length=10)
    country = models.CharField(max_length=50)
    health = tinymce_models.HTMLField(null=True, blank=True)
    economy = tinymce_models.HTMLField(null=True, blank=True)
    environment = tinymce_models.HTMLField(null=True, blank=True)
    governance = tinymce_models.HTMLField(null=True, blank=True)
    infrastructure = tinymce_models.HTMLField(null=True, blank=True)
    social_sector = tinymce_models.HTMLField(null=True, blank=True)
    agriculture = tinymce_models.HTMLField(null=True, blank=True)
    dev_partners = tinymce_models.HTMLField(null=True, blank=True)
    recent_reports = tinymce_models.HTMLField(null=True, blank=True)
    resources = tinymce_models.HTMLField(null=True, blank=True)

    class Admin:
        pass
   
        
class ReviewFeedback(models.Model):
    feedback = models.CharField(max_length=1000)
    project = models.ForeignKey(Project)
    reviewed_by = models.ForeignKey(User)
    viewed = models.BooleanField(default=False)
    date = models.DateTimeField()
    
    class Meta:
        ordering = ('-date', 'viewed')
    
    
    class Admin:
        pass
    
class ProjectComment(models.Model):
    text = models.CharField(max_length=1000)
    status = models.CharField(max_length=20)
    project = models.ForeignKey(Project)
    comment_by = models.CharField(max_length=100)
    email = models.EmailField()
    date = models.DateTimeField()
    
    def __unicode__(self):
        return self.text
        
    class Admin:
        pass
        
class Video(models.Model):
    provider = models.CharField(max_length=50)
    video_id = models.CharField(max_length=50)
    project = models.ForeignKey(Project)
    default = models.BooleanField(default=False)
    url = models.CharField(max_length=500)
    
    def __unicode__(self):
        return self.provider + self.video_id
        
    class Admin:
        pass
        
        
class KMLFile(models.Model): 
    name = models.CharField(max_length=50)
    filename = models.CharField(max_length=500)
    
    def __unicode__(self):
        return self.name
        
    class Admin:
        pass

maplayers/forms.py
from django import forms
from django.forms.util import ErrorList
from tinymce.widgets import TinyMCE

from maplayers.countries import COUNTRIES
from maplayers.models import Project
from decimal import Decimal
from maplayers.models import Sector, Implementor
from django.contrib.auth.models import User
from maplayers.geoserver import GeoServer

def _get_sectors():
    return tuple([(sector.id, sector.name) for sector in Sector.objects.all()])
    
def _get_implementors():
    return tuple([(implementor.id, implementor.name) for implementor in Implementor.objects.all()])
    
class ProjectForm(forms.Form):
    name = forms.CharField(max_length=30) 
    description = forms.CharField(widget=TinyMCE(attrs={'cols' : 80, 'rows' : 20}))
    latitude = forms.DecimalField()
    longitude = forms.DecimalField()
    location = forms.CharField(max_length=50)
    website_url = forms.URLField()
    project_sectors = forms.MultipleChoiceField(required=True)
    project_implementors = forms.MultipleChoiceField(required=True)
    imageset_feedurl = forms.CharField(max_length=1000, required=False)
    tags = forms.CharField(max_length=500, required=False)
    
    def __init__(self, *args, **kwargs):
        self.base_fields['project_sectors'].choices = _get_sectors()
        self.base_fields['project_implementors'].choices = _get_implementors()
        super(ProjectForm, self).__init__(*args, **kwargs)
           
    
    def clean_latitude(self):
        cleaned_data = self.cleaned_data
        lat = cleaned_data.get("latitude")
        if lat<-90 or lat>90:
            self._errors['latitude'] = ErrorList([u'Latitude should be between -90 to 90'])
        lat = lat.quantize(Decimal('.0000001'))
        return lat
        
    def clean_longitude(self):
        cleaned_data = self.cleaned_data
        lon = cleaned_data.get("longitude")
        if lon<-180 or lon>180:
            self._errors['longitude'] = ErrorList([u'Longitude should be between -180 to 180'])
        lon = lon.quantize(Decimal('.0000001'))
        return lon
    
class AdminUnitForm(forms.Form):
    name = forms.CharField(max_length=50, required=True)
    region_type = forms.CharField(max_length=20, required=True)
    country = forms.ChoiceField(choices=COUNTRIES)
    health = forms.CharField(widget=TinyMCE(attrs={'cols':50, 'rows':10}), required=False)
    economy = forms.CharField(widget=TinyMCE(attrs={'cols':50, 'rows':10}), required=False)
    environment = forms.CharField(widget=TinyMCE(attrs={'cols':50, 'rows':10}), required=False)
    governance = forms.CharField(widget=TinyMCE(attrs={'cols':50, 'rows':10}), required=False)
    infrastructure = forms.CharField(widget=TinyMCE(attrs={'cols':50, 'rows':10}), required=False)
    social_sector = forms.CharField(widget=TinyMCE(attrs={'cols':50, 'rows':10}), required=False)
    agriculture = forms.CharField(widget=TinyMCE(attrs={'cols':50, 'rows':10}), required=False)
    dev_partners = forms.CharField(widget=TinyMCE(attrs={'cols':50, 'rows':10}), required=False)
    recent_reports = forms.CharField(widget=TinyMCE(attrs={'cols':50, 'rows':10}), required=False)
    resources = forms.CharField(widget=TinyMCE(attrs={'cols':50, 'rows':10}), required=False)
    
    
class UserForm(forms.Form):
    username = forms.CharField(max_length=30) 
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput())
    confirm_password = forms.CharField(widget=forms.PasswordInput())
    
    def clean_username(self):
        cleaned_data = self.cleaned_data
        username = cleaned_data.get('username')
        user = User.objects.filter(username=username)
        if user:
            self._errors["username"] = ErrorList([u'Sorry, the user Name is not available'])
        return username


    def clean(self):
        cleaned_data = self.cleaned_data
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")
        
        if password != confirm_password:
            message = u"Passwords do not match"
            self._errors["password"] = ErrorList([message])
            
        return cleaned_data
        
class ChangePasswordForm(forms.Form):
    old_password = forms.CharField(widget=forms.PasswordInput())
    new_password = forms.CharField(widget=forms.PasswordInput())
    confirm_password = forms.CharField(widget=forms.PasswordInput())
    
    def clean(self):
        cleaned_data = self.cleaned_data
        new_password = cleaned_data.get("new_password")
        confirm_password = cleaned_data.get("confirm_password")
        
        if new_password != confirm_password:
            message = u"Passwords do not match"
            self._errors["new_password"] = ErrorList([message])
        return cleaned_data
        
    def validated_user(self, user):
        cleaned_data = self.cleaned_data
        old_password = cleaned_data.get("old_password")
        
        if not user.check_password(str(old_password)):
            self._errors["old_password"] = ErrorList(["Incorrect password"])
            return False
            
        return True
        
class KMLFilesForm(forms.Form):
    name = forms.CharField(max_length = 50)
    filename = forms.FileField()

        

maplayers/templates/add_admin_unit.html
{% extends "base.html" %}
{% load i18n %}

{% block title_extra %} &mdash; Add Administrative Unit {% endblock %}
{% block extrahead %}
<script src="{{ jquery }}" type="text/javascript"></script>
<script type="text/javascript" src="{{ tinymce_url }}"></script>
<script type="text/javascript">
$(document).ready(function(){
	$(".togglefield").click(function(){
		var id_name = this.id.substring(3);
		if($(this).attr("show") == "true"){
			$(this).html("[+]");
			$("#"+id_name).hide();
			$(this).attr("show", "false");
		}else{
			$(this).html("[-]");
			$("#"+id_name).show();
			$(this).attr("show", "true");
		}
	});	
});

</script>
{% endblock %}
{% block page_content %}
<div id="add_admin_unit">
<form action="/{{action}}/" method="post">
	<fieldset>
    	<legend><span>Administrative Details</span></legend>				
			<div>
				<label for="id_name">Region Name:</label> 
				{{form.name}}
				{{ form.name.errors }}
			</div>
			<div class="clearleft">
				<label for="id_country">Country:</label> 
                {{ form.country }}
				{{ form.country.errors }}
			</div>
			<div>
				<label for="id_region_type">Region type:</label> 
				{{ form.region_type }}
				{{ form.region_type.errors }}
			</div>
			<div class="details_div">
				<a class="togglefield" id="id-health" show="false">[+]</a>							
				<label for="id_health">Health:</label>
				<div id="health" style="display:none">{{ form.health}}</div>
				{{ form.health.errors}}				
			</div>
			
			<div class="details_div">
				<a class="togglefield" id="id-economy" show="false">[+]</a>			
				<label for="id_economy">Economy:</label>
				<div id="economy" style="display:none">{{ form.economy}}</div>
				{{ form.economy.errors}}
			</div>
			
			<div class="details_div">
				<a class="togglefield" id="id-environment" show="false">[+]</a>			
				<label for="id_environment">Environment:</label>
				<div id="environment" style="display:none">{{ form.environment}}</div>
				{{ form.environment.errors}}
			</div>
			
			<div class="details_div">
				<a class="togglefield" id="id-governance" show="false">[+]</a>			
				<label for="id_governance">Governance:</label>
				<div id="governance" style="display:none">{{ form.governance}}</div>
				{{ form.governance.errors}}
			</div>
			
			<div class="details_div">
				<a class="togglefield" id="id-infrastructure" show="false">[+]</a>			
				<label for="id_infrastructure">Infrastructure:</label>
				<div id="infrastructure" style="display:none">{{ form.infrastructure}}</div>
				{{ form.infrastructure.errors}}
			</div>
			
			<div class="details_div">
				<a class="togglefield" id="id-social_sector" show="false">[+]</a>			
				<label for="id_social_sector">Social Sector:</label>
				<div id="social_sector" style="display:none">{{ form.social_sector}}</div>
				{{ form.social_sector.errors}}
			</div>
			
			<div class="details_div">
				<a class="togglefield" id="id-agriculture" show="false">[+]</a>			
				<label for="id_agriculture">Agriculture:</label>
				<div id="agriculture" style="display:none">{{ form.agriculture}}</div>
				{{ form.agriculture.errors}}
			</div>
			
			<div class="details_div">
				<a class="togglefield" id="id-dev_partners" show="false">[+]</a>			
				<label for="id_dev_partners">Dev Partners:</label>
				<div id="dev_partners" style="display:none">{{ form.dev_partners}}</div>
				{{ form.dev_partners.errors}}
			</div>
			
			<div class="details_div">
				<a class="togglefield" id="id-recent_reports" show="false">[+]</a>			
				<label for="id_recent_reports">Recent Reports:</label>
				<div id="recent_reports" style="display:none">{{ form.recent_reports}}</div>
				{{ form.recent_reports.errors}}
			</div>
			
			<div class="details_div">
				<a class="togglefield" id="id-resources" show="false">[+]</a>			
				<label for="id_resources">Resources:</label>
				<div id="resources" style="display:none">{{ form.resources}}</div>
				{{ form.resources.errors}}
			</div>
		</fieldset>
        <div class="main_action">
            <input type="submit" value="Save" />
        </div>
</form>
</div>
{% endblock %}

maplayers/templates/add_kml_files.html
{% extends "base.html" %}
{% load i18n %}
{% load project_tags %}

{% block title_extra %} Add KML file {% endblock %}

{% block extrahead %}
		<link type="text/css" href="{{ css_url }}/dialog.css" rel="stylesheet" />
		<script type="text/javascript">
			var delete_kml_url;
			var delete_tr;
		</script>
		
		<script src="{{ jquery }}" type="text/javascript"></script>
		<script type="text/javascript" src="{{ jqueryui }}"></script>
        <script type="text/javascript" src="{{ js_url }}/kml.js"></script>	
			
{% endblock %}



{% block page_content %}
<div id="add_kml_file">
	<h2>Add KML Files:</h2>
	<form action="/add_kml/" method="post" enctype="multipart/form-data">
		{{ form.as_p }}
		<input type="submit" value="submit"/>
	</form>
	
	{% if existing_kmls %}
	<div id="current_list_of_kmls">
		<h4>Current List of KMLs</h4>
		
		<table id="kml_list">
		<tr>
			<th>Name</th>
			<th>Action</th>
		</tr>
		
		{% for existing_kml in existing_kmls %}
			<tr id="kml_file_{{existing_kml.id}}">
				<td><a href="/{{existing_kml.filename}}">{{existing_kml}}</a></td>
				<td><span id="delete_kml_file_{{existing_kml.id}}" class="delete_link">Delete</td>
			</tr>	
		{% endfor %}
		</table>
	</div>	
	{% endif %}
	
	<div id="delete_dialog" title="Delete KML !">
		<p>Are you Sure you want to delete this kml layer ?</p>
	</div>
</div>	
{% endblock %}

maplayers/templates/all_comments.html
{% extends "base.html" %}
{% load i18n %}
{% load project_tags %}

{% block title_extra %} {{ project.name }} {% endblock %}

{% block extrahead %}
        <script type="text/javascript" src="{{ js_url }}/all_project_comments.js"></script>
        <script type="text/javascript">
			project_id = "{{project.id}}"; 
		</script>
{% endblock %}

{% block page_content %}
	<div id="project_all_comments">
			<div class="head_nav">
				<h4 class="floatleft">{{project.name}} comments</h4>
				<a class="floatright" href="/projects/id/{{project.id}}/"> << Back to project</a>
			</div>
		{% project_comments project mode '-1' %}
	</div>
{% endblock %}

maplayers/templates/gallery.html
{% extends "base.html" %}
{% load i18n %}

{% block title_extra %} &mdash; Test Gallery{% endblock %}
{% block page_content %}
<div id="image_set">
{% load project_tags %}
{% parse_img_rss_feed %}
<ul>
  {% for img in rss_img_feed.images %}
    <li>
      <div>
        <a href={{img.entry_url}}><img src={{img.img_url}} /></a>
      </div>
        <div>{{img.title}}</div>
    </li>   
  {% endfor %}
  </ul>
 </div>
{% endblock %}

maplayers/templates/my_projects.html
{% extends "base.html" %}
{% load i18n %}
{% load project_tags %}

{% block title_extra %} My Projects {% endblock %}
{% block extrahead %}
		<link type="text/css" href="{{ css_url }}/dialog.css" rel="stylesheet" />

		<script src="{{ jquery }}" type="text/javascript"></script>
		<script type="text/javascript" src="{{ jqueryui }}"></script>
        <script type="text/javascript" src="{{ js_url }}/my_projects.js"></script>		
{% endblock %}

{% block page_content %}
	<div id="my_projects">
		<h2>My Projects: </h2>
		{% if projects %}
			<table id="my_project_list">
			{% my_projects_header user %}
			{% for project in projects %}
				{% my_project project user %}
			{% endfor %}
			</table>
		{% else %}
			<p>No projects</p>
		{% endif %}
	</div>
	
	
	<div id="dialog" title="Review Suggestions"></div>
	
{% endblock %}

maplayers/templates/permission_denied.html
{% extends "base.html" %}
{% load i18n %}

{% block title_extra %} &mdash; Not Allowed{% endblock %}
{% block page_content %}
<div>
    Sorry, you cannot {% trans params.action %} because {% trans params.reason %}
</div>
<div>
    <a href='/'>click here to return home</a>
 </div>
{% endblock %}

maplayers/templates/project_comments.html
{% extends "base.html" %}
{% load i18n %}
{% load project_tags %}

{% block title_extra %} Comments{% endblock %}

{% block extrahead %}
	<script src="{{ jquery }}" type="text/javascript"></script>
	<script type="text/javascript" src="{{ js_url }}/project_comments.js"></script>
{% endblock %}



{% block page_content %}
<div id="project_comments">
	<h2>{{project.name}}</h2>
	
	<form action="" method="post" id="comments_form">
		<div>
			<span class="publish_comment">Publish</span>
			<span class="delete_comment">Delete</span>
		</div>
		
		<div id="comments">
		{% for comment in comments %}
			<div id="comment_{{comment.id}}">
				<input type="checkbox" name="comment_{{comment.id}}" />
				<span class="comment_text">{{comment.text}}</span>
				<p class="comment_metainfo">
					<span class="comment_by">By: {{comment.comment_by}},</span>
					<span class="comment_date">{{comment.date|date:"F j, Y"}}</span>
				</p>
			</div>
		{% endfor %}
		</div>
		
		<input type="hidden" name="project_id" value="{{project.id}}"/>
	</form>
</div>
{% endblock %}

maplayers/templates/project_created_successfully.html
{% extends "base.html" %}
{% load i18n %}

{% block title_extra %} &mdash; {{ project.name }} Created{% endblock %}
{% block page_content %}
	Project created successfully<br/>
	<a href="/add_project">Add another</a>
{% endblock %}

maplayers/templates/projects_for_review.html
{% extends "base.html" %}
{% load i18n %}
{% load project_tags %}

{% block title_extra %} My Projects {% endblock %}
{% block extrahead %}
		<link rel="stylesheet" href="{{ css_url }}/projects_for_review.css" type="text/css" />
		<link type="text/css" href="{{ css_url }}/dialog.css" rel="stylesheet" />
		
		<script src="{{ jquery }}" type="text/javascript"></script>
		<script type="text/javascript" src="{{ jqueryui }}"></script>
		
 		<script type="text/javascript">
			var project_id;
			var delete_url;
			var delete_tr;
		</script>
		
        <script type="text/javascript" src="{{ js_url }}/projects_for_review.js"></script>				
{% endblock %}

{% block page_content %}
	<div id="projects_for_review">
	<h2>Projects for Review: </h2>
	{% if projects %}
		<table id="project_list">
		<tr>
			<th>Project title</th>
			<th>Created by</th>
			<th>Action</th>
		</tr>
		{% for project in projects %}
			<tr id="project_{{project.id}}">
				<td><a href="/projects/id/{{project.id}}/">{{project.name}}</a></td>
				<td>{{project.created_by}}</td>
				<td>
					<span class="first"><a href="/edit_project/{{project.id}}/">Edit</a></span>
					<span class="review_suggestions" id="review_{{project.id}}">Provide Feedback</span>
					<span class="publish_link" id="publish_{{project.id}}">Publish</span>
					<span class="reject_link" id="reject_{{project.id}}">Reject</span>
					<span class="delete_link" id="delete_{{project.id}}">Delete</span>
				</td>
			</tr>
		{% endfor %}
		</table>
	{% else %}
		<div>No projects to review</div>
	{% endif %}
	<div id="dialog" title="Review Suggestions">
		<form id="project_feedback">
			<textarea rows="8" cols="35" name="feedback" id="feedback"></textarea>
		</form>
	</div>
	
	<div id="delete_dialog" title="Delete Project !">
		<p>Are you Sure you want to delete this project ?</p>
	</div>

	
{% endblock %}